services:
  postgres:
    image: postgres:16-alpine
    container_name: imgproc-postgres
    environment:
      POSTGRES_USER: imgproc_user
      POSTGRES_PASSWORD: imgproc_password
      POSTGRES_DB: imgproc_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imgproc_user -d imgproc_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
